PC-9234 Replace old client and sdk with new ones
nobl9/terraform-provider-nobl9 pull request #113
Opened 2023-08-10 13:40 UTC by BSski

TBA

2023-10-11 09:01 UTC, nieomylnieja requested changes

2023-10-13 12:48 UTC, BSski commented on nobl9/metadata_schema.go
> +				labelValuesStr = append(labelValuesStr, labelValueRaw)
From what I see it also has parts related to e.g. schemas of Name, Display Name, Description and Project. Am I missing something?

2023-10-16 12:55 UTC, nieomylnieja commented on nobl9/metadata_schema.go
> +				labelValuesStr = append(labelValuesStr, labelValueRaw)
ah damn, my bad I missed it :D

2023-10-17 11:45 UTC, BSski commented on nobl9/resource_agent.go
> +	data, err := json.Marshal(objects)
Good catch, I was waiting for this one to get implemented and missed it later. Thanks!

2023-10-19 13:42 UTC, nieomylnieja approved these changes

2023-10-19 13:42 UTC, nieomylnieja commented on examples/provider/provider.tf
> +      version = "0.16.0"
please remove `organization` and `project` from the below example, let's keep it minimal:

```terraform
provider "nobl9" {
  client_id     = "<client_id>"
  client_secret = "<client_secret>"
}
```

2023-10-20 10:21 UTC, nieomylnieja submitted a review, later dismissed

2023-10-25 09:46 UTC, merged