PC-10929 terraform always wants to update direct datasource if release channel is not provided
nobl9/terraform-provider-nobl9 pull request #130
Opened 2023-11-15 12:38 UTC by kubaceg

2023-11-15 14:46 UTC, klaudia-nobl9 commented
Tested, LGTM 👌 
- `release_channel` validation fixed
- bug related to reapplying the same direct/agent config without `release_channel`  fixed

2023-11-16 08:58 UTC, nieomylnieja requested changes

2023-11-16 08:58 UTC, nieomylnieja commented on nobl9/release_channel_schema.go
> +			validation.StringInSlice([]string{"stable", "beta"}, false),
There's an enum for these in SDK:
```suggestion
			validation.StringInSlice([]string{v1alpha.ReleaseChannelStable.String(), v1alpha.ReleaseChannelBeta.String()}, false),
```

2023-11-16 14:40 UTC, nieomylnieja approved these changes

2023-11-16 14:41 UTC, merged