feat: PC-11815 add budget adjustments terraform support
nobl9/terraform-provider-nobl9 pull request #175
Opened 2024-02-22 15:06 UTC by kubaceg

## Motivation

Add support for the new `BudgetAdjustment` kind.

## Release Notes

New BudgetAdjustment kind which allows customers to schedule recurring future events that should be excluded from the Error Budget calculations in their SLOs. This PR introduces new `budget_adjustment` resource.

2024-02-29 09:56 UTC, labtom requested changes

2024-02-29 09:56 UTC, labtom commented on nobl9/resource_budgetadjustment.go
> +				"The expected value is a string in time duration string format. " +
```suggestion
				"The expected value for this field is a string formatted as a time duration. " +
```

2024-02-29 09:56 UTC, labtom commented on nobl9/resource_budgetadjustment.go
> +				"Duration must be defined with 1 minute precision." +
```suggestion
				"The duration must be defined with a precision of 1 minute." +
```

2024-03-06 07:16 UTC, labtom submitted a review, later dismissed
JZK

2024-05-06 12:20 UTC, nieomylnieja requested changes

2024-05-06 12:20 UTC, nieomylnieja commented on nobl9/resource_budgetadjustment.go
> +	budgetAdjustment := marshalBudgetAdjustment(d)
shadows budgetAdjustment() function, maybe just (or `bg`):

```suggestion
	adjustment := marshalBudgetAdjustment(d)
```

2024-05-06 12:20 UTC, nieomylnieja commented on nobl9/resource_budgetadjustment.go
> +	diags = appendError(diags, err)
wouldn't it be simpler to simply write:

```suggestion
	diags = appendError(diags, d.Set("name", object.Metadata.Name))
```

2024-05-06 12:47 UTC, nieomylnieja approved these changes
looks good!

2024-05-14 09:02 UTC, merged