feat: PC-11745 Add primary objective terraform support
nobl9/terraform-provider-nobl9 pull request #202
Opened 2024-03-20 14:03 UTC by natalialanga

## Summary

Add primary objective terraform support

## Related changes

[sdk](https://github.com/nobl9/nobl9-go/pull/330)

## Testing

Build a local provider with make install and use the sample .tf file for testing.

Sample .tf file:

```
terraform {
  required_providers {
    nobl9 = {
      source  = "nobl9.com/nobl9/nobl9"
      version = "0.25.0"
    }
  }
}

// Fill using nobl9 auth configuration
provider "nobl9" {
  ingest_url       = ""
  okta_org_url     = ""
  okta_auth_server = ""
  client_id        = ""
  client_secret    = ""
}

resource "nobl9_slo" "this" {
  name             = "slo"
  service          = "service"
  budgeting_method = "Occurrences"
  project          = "project"

  time_window {
    unit       = "Day"
    count      = 30
    is_rolling = true
  }

  objective {
    name         = "obj-1"
    target       = 0.99
    value        = 2000
    op           = "gte"
    primary      = true

    raw_metric {
      query {
        prometheus {
          promql = "query"
        }
      }
    }
  }

  indicator {
    name = "test-prom-agent"
  }
}
```

2024-03-27 12:40 UTC, paulina-n9 commented
lgtm 👌🏻

2024-04-08 09:42 UTC, lukasz-dobek submitted a review, later dismissed
LGTM, with the assumption that we will release 0.25 😄

2024-04-08 09:59 UTC, nieomylnieja requested changes

2024-04-08 09:59 UTC, nieomylnieja commented on go.mod
> +toolchain go1.22.2
remove this:

```suggestion
toolchain go1.22.2
```

2024-04-08 10:19 UTC, nieomylnieja approved these changes

2024-04-08 10:25 UTC, merged