feat: PC-13893 objective's value is optional for Composite SLOs
nobl9/terraform-provider-nobl9 pull request #295
Opened 2024-08-23 14:02 UTC by ditrytus

## Motivation

Describe what is the motivation behind the proposed changes.
If possible reference the current solution/state of affairs.

## Summary

Recap of changed code.

## Related Changes

List related changes from other PRs (if any).

## Testing

- Describe how to check introduced code changes manually.
- Take care of test coverage on unit, integration or end-to-end levels.

## Release Notes

If this change should be part of the Release Notes,
**replace this entire paragraph** with 1-3 sentences about the changes.
Otherwise, you **MUST** remove this section entirely.

Does this PR contain any breaking changes?
If so, add `## Breaking Changes` header and list the introduced changes there.

2024-09-13 09:03 UTC, piotrkwarcinski requested changes
I'm no terraform expert but I tested the code running it locally and its logic works as it should:
* when `value = 0` composite slo is created
* when `value!=0` there's an error
* when `value` doesn't exist composite slo is created

but I noticed that when you don't pass `value` terraform apply shows:
```
(⎈|arn:aws:eks:eu-central-1:922330643383:cluster/dev-demo-4:flink)➜  comp-val-test git:(PC-13893-composite-value) ✗ terraform apply                         
nobl9_project.test: Refreshing state... [id=pkw-test-tf]
nobl9_service.test: Refreshing state... [id=pkw]
nobl9_slo.composite_slo: Refreshing state... [id=pkw-test-tf-composite]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # nobl9_slo.composite_slo will be updated in-place
  ~ resource "nobl9_slo" "composite_slo" {
        id               = "pkw-test-tf-composite"
        name             = "pkw-test-tf-composite"
        # (6 unchanged attributes hidden)

      - objective {
          - display_name      = "OK" -> null
          - name              = "tf-objective-1" -> null
          - primary           = false -> null
          - target            = 0.8 -> null
          - time_slice_target = 0 -> null
          - value             = 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005 -> null
            # (1 unchanged attribute hidden)

          - composite {
              - max_delay = "45m" -> null

              - components {
                  - objectives {
                    }
                }
            }
        }
      + objective {
          + display_name = "OK"
          + name         = "tf-objective-1"
          + target       = 0.8
          + value        = 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005
            # (1 unchanged attribute hidden)

          + composite {
              + max_delay = "45m"

              + components {}
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Warning: SLO objective unique identifier warning
│ 
│   with nobl9_slo.composite_slo,
│   on entire-budget.test.tf line 29, in resource "nobl9_slo" "composite_slo":
│   29: resource "nobl9_slo" "composite_slo" {
│ 
│ Nobl9 is introducing an SLO objective unique identifier to support the same value for different SLIs in the same SLO. As such, Nobl9 is adding a name identifier to
│ each SLO objective. Objective names can be set now, and they'll be required once grace period ends. For more detailed information, refer to:
│ https://docs.nobl9.com/features/slo-objective-unique-identifier
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
```
Notice how `value` is a very long string when I didn't even specified it in my terraform resource I tried to apply:
```
terraform {
  required_providers {
    nobl9 = {
      source  = "nobl9.com/nobl9/nobl9"
      version = "0.29.2"
    }
  }
}

provider "nobl9" {
  organization     = "nobl9-dev"
  project          = "default"
  ingest_url       = "https://dev-demo-1.nobl9.dev/api"
  okta_org_url     = "https://accounts.nobl9.dev"
  okta_auth_server = ""
  client_id        = ""
  client_secret    = ""
}

resource "nobl9_project" "test" {
  name = "pkw-test-tf"
}

resource "nobl9_service" "test" {
  name    = "pkw"
  project = "pkw-test-tf"
}

resource "nobl9_slo" "composite_slo" {
  name             = "${nobl9_project.test.name}-composite"
  service          = nobl9_service.test.name
  budgeting_method = "Occurrences"
  project          = nobl9_project.test.name

  time_window {
    unit       = "Day"
    count      = 3
    is_rolling = true
  }

  objective {
    display_name = "OK"
    name         = "tf-objective-1"
    target       = 0.8
    composite {
      max_delay = "45m"
      components {
      }
    }
  }
}
```  
I think this value can be a little confusing to users, perhaps there is a way to avoid displaying it?

2024-09-13 10:54 UTC, ditrytus commented on nobl9/resource_slo_test.go
> -   value        = 1
I added a separate test for that. I wanted to explicitly test it without value too.

2024-09-13 10:58 UTC, ditrytus commented
I removed the sentinel altogether and now I'm just setting `value` to default `0`. This doesn't produce any weird plans and regardless of whether the user is adding `value: 0` to composite or not it doesn't recognize it as an update, so I think it works even better.

2024-09-13 12:21 UTC, piotrkwarcinski submitted a review, later dismissed
lgtm!

2024-12-09 11:43 UTC, piotrkwarcinski approved these changes

2024-12-09 11:44 UTC, merged