Support Anomaly Config in SLO Spec
nobl9/terraform-provider-nobl9 pull request #95
Opened 2023-04-18 13:38 UTC by nuusk

2023-04-26 08:46 UTC, nuusk commented on go.mod
> +replace github.com/nobl9/nobl9-go v0.7.3 => ../nobl9-go
This will be removed before merging and releasing nobl9-go

2023-04-26 11:23 UTC, piotrkwarcinski requested changes
I left a few suggestions for now :), when it's ready I'll do the review again. I didn't comment on commented tests and  the `TF_ACC` flag but I suspect those are temporary changes and will be fixed when the PR is ready.
Btw. I tried to run the current version of the code and it doesn't seem to work:
```
Stack trace from the terraform-provider-nobl9 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 71 [running]:
github.com/nobl9/terraform-provider-nobl9/nobl9.unmarshalAnomalyConfig(0xc00020b580?, 0xc8608c?)
        /home/piotr/dev/terraform-provider-nobl9/nobl9/anomaly_config_schema.go:131 +0x45c
github.com/nobl9/terraform-provider-nobl9/nobl9.unmarshalSLO(0xc0006861c8?, {0xc0004f8040?, 0x3?, 0x0?})
        /home/piotr/dev/terraform-provider-nobl9/nobl9/resource_slo.go:702 +0xfad
github.com/nobl9/terraform-provider-nobl9/nobl9.resourceSLORead({0xdbdc60?, 0xc000249830?}, 0xc00020b580, {0xc48940?, 0xc00068e230?})
        /home/piotr/dev/terraform-provider-nobl9/nobl9/resource_slo.go:372 +0x305
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0004abea0, {0xdbdc60, 0xc000249830}, 0xd?, {0xc48940, 0xc00068e230})
        /home/piotr/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.19.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004abea0, {0xdbdc60, 0xc000249830}, 0xc0001d9520, {0xc48940, 0xc00068e230})
        /home/piotr/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.19.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0004787e0, {0xdbdc60?, 0xc0002496e0?}, 0xc00011a880)
        /home/piotr/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.19.0/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0003beb40, {0xdbdc60?, 0xc000248ab0?}, 0xc0006ca480)
        /home/piotr/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/tf5server/server.go:747 +0x423
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xc570a0?, 0xc0003beb40}, {0xdbdc60, 0xc000248ab0}, 0xc00068e000, 0x0)
        /home/piotr/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ca1e0, {0xdc1b38, 0xc000288d00}, 0xc00034b9e0, 0xc00048f620, 0x127d4d0, 0x0)
        /home/piotr/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc0001ca1e0, {0xdc1b38, 0xc000288d00}, 0xc00034b9e0, 0x0)
        /home/piotr/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/piotr/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/piotr/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-nobl9 plugin crashed!
```

2023-04-26 11:23 UTC, piotrkwarcinski commented on nobl9/anomaly_config_schema.go
> +		result[method.Name] = values
```suggestion
		result[method.Name] = map[string]string{
			"name": method.Name,
			"project": method.Project,
		}
```
For me it's more readable, but you can leave it the way it is, only maybe remove the empty line.

2023-04-26 11:23 UTC, piotrkwarcinski commented on nobl9/resource_slo.go
> +	return d.Set("time_window", y)
How about?
```suggestion
	tw := schema.NewSet(oneElementSet, []interface{}{timeWindowsTF})
	return d.Set("time_window", tw)
```

2023-04-26 12:58 UTC, klaudia-nobl9 commented
I've tested it and I haven't found any other bugs other than the problem we've already discussed in regards to removing anomalyConfig from the SLO resource.

For the sake of documentation, I'm adding steps to reproduce mentioned error:
1. Apply the .tf with SLO resource with anomaly_config block with couple of Alert Methods.
2. Remove anomaly_config block and try to reapply the .tf file. 

Actual result: After deleting the entire anomaly_config block, Terraform sees no changes to the configuration and returns the message: `No changes. Your infrastructure matches the configuration.`
Expected result: Terraform should detect configuration changes.

Similar bug was noted during our work on labels: https://github.com/nobl9/terraform-provider-nobl9/pull/45#issuecomment-1220546213

2023-05-05 11:20 UTC, klaudia-nobl9 commented
Works flawlessly 🌻

2023-05-07 17:21 UTC, nuusk commented on nobl9/anomaly_config_schema.go
> +								Elem: &schema.Resource{
We're not sure how this structure will look like in the future so I think it's better to have it all here for simplicity

2023-05-07 17:23 UTC, nuusk commented on nobl9/resource_slo.go
> +	return d.Set("time_window", y)
thx, it was a typo :)

2023-05-08 10:19 UTC, piotrkwarcinski submitted a review, later dismissed
Tested locally, works now as expected :rocket: , I left one more comment to sort some imports before merging.

2023-05-08 10:19 UTC, piotrkwarcinski commented on nobl9/anomaly_config_schema_test.go
> +	"github.com/stretchr/testify/assert"
please sort these imports before merging

2023-05-08 10:35 UTC, piotrkwarcinski approved these changes

2023-05-08 10:35 UTC, piotrkwarcinski approved these changes

2023-05-08 10:55 UTC, klaudia-nobl9 commented
Did some smoke testing after bumbing nobl9-go, works as expected 🚀

2023-05-08 12:01 UTC, merged